### ISSUE TITLE
"The field 'images' does not allow null values."

### ISSUE THREAD

**Issue by hounddog22030** [worstone/BigCommerce4Net#12]
I am attempting to create new products.

When calling 
    var x = client.Products.Create(p);

I get an error response of "The field 'images' does not allow null values."

I have create a new ProductImage and attached it, that doesn't work.
I have queried the ProductImages and attached one of them, that doesn't work.
I have created an empty collection and set it onto the product, that does work.

I reviewed the BigCommerce API documentation, it reads that images is readonly.

Any thoughts?

Thanks

**Comment by worstone** [comment]
Try something like this, there is no support for uploading of the image files in this api.

Hope this helps

```csharp
var product = new {
    Name = "Product Name.....",
    Sku = "Sku.....",
    Description = "Description....."
    ...
};
var response_product = Client.Products.Create(product);
var new_product = response_product.Data;

if (response_product.ResponseErrors == null && new_product != null) {

    var product_image = new {
    image_file = "i/866/HydromaticSPD100_w__41534.jpg",
    Description = "Description....."
    ...
    };
    var response_product_image = Client.ProductsImages.Create(new_product.Id, product_image);

    if (response_product_image.ResponseErrors == null && response_product_image.Data != null) {
                    //You now have added a new product_image
    }
}
```

**Comment by hounddog22030** [comment]
Thanks for your reply.

Yeah, I'm just trying to get something into the database (doing a spike).  I don't care if it has images or not.

Do nothing with the product's Images Collection (Images Property) yields the response of ""The field 'images' does not allow null values.""  at line Client.Products.Create(product).

**Comment by worstone** [comment]
Did you in include the image_file property?  

The BigCommerce Documentation says the product image (image_file) is required

BigCommerce Documentation- https://developer.bigcommerce.com/api/stores/v2/products/images

I really have not tested the ProductsImages.Create, maybe the file needs to be on the server before creating the record, not sure.

**Comment by worstone** [comment]
Product image (image_file) is just the path to the image not the image file.
