### ISSUE TITLE
Null Value

### ISSUE THREAD

**Issue by DanKimble** [worstone/BigCommerce4Net#14]
Trying to pull a list of all categories:
List<BigCommerce4Net.Domain.Category> bcCategories = bcClient.Categories.GetList().ToList();

When I do I get a "Null Value" exception in BigCommerce4Net.Api.ClientBase.RecordPaging on line 290:
itemsCount = ((Domain.ItemCount)client.Count(filter).Data).Count;

**Comment by DanKimble** [comment]
Found the issue. I had the wrong credentials in the code. I noticed you check for throttling - might be a good idea to check for invalid credentials and throw that error.

**Comment by worstone** [comment]
Dan,

You are more than welcome to submit a Pull Request that checks for invalid credentials.
