### ISSUE TITLE
The field 'images' does not allow null values.

### ISSUE THREAD

**Issue by Artyfice** [worstone/BigCommerce4Net#15]
I know this question has been asked before but there is no answer to it.
I got this message when trying to create a new product.

I tried adding an image to `Product.Images` but it didn't help.

Digging in the `Product` class I found:

`[JsonProperty("images")]`
`public virtual Resource ResourceImages { get; set; }`

`[JsonIgnore]`
`public virtual IList<ProductsImage> Images { get; set; }`

I then populated `ResourceImages` instead but I got **"The field 'images' cannot be written to. Please remove it from your request before trying again"**.

My temporary fix is to flag `ResourceImages` as `[JsonIgnore]`, as well as all the other `Resource`s.

Is there another way to do it?

**Comment by worstone** [comment]
I hate the way the BC does Product Resources in their API or any other resources for that matter, they will not take nested json or xml and must be treated as two separate POST operations. The same goes for GET requests.

1. Use ClientProducts to add the Product 
2. Once added get the product id so you can add the ProductsImage 
3. Use ClientProductsImages  to add the product images

https://developer.bigcommerce.com/api/products

Hope that helps

Ken Worst

**Comment by Artyfice** [comment]
Thanks for your answer. The problem is that I can't create a product with `ClientProducts.Create(object obj)`. This method will use `obj.SerializeObject()' which will add `"images":null` to the json. Unless I tag `public virtual Resource ResourceImages { get; set; }` as `[JsonIgnore]` - `public virtual IList<ProductsImage> Images { get; set; }` is already tagged as `[JsonIgnore]`.

**Comment by worstone** [comment]
I see now (little rusty on this code base), I would used Anonymous Types for the Product or you could roll your own when doing a POST that way you have full control of what is Serialized to Json.

The Create Method takes Json or an Object

`Create(object obj)`
`Create(string json)`

I couldn't come up with a way for the Resources objects to act as both when it comes the serialization without creating two different objects.

Hope that helps

Ken Worst
