### ISSUE TITLE
Attempts to update Statusid/status fails

### ISSUE THREAD

**Issue by tossthekitty** [worstone/BigCommerce4Net#18]
When I attempt to update the status of an order as Shipped trying:
                   Order toUpdate = client.Orders.Get( orderId ).Data;
                    if(toUpdate == null)
                        goto OOPS;
                    toUpdate.Status = isShipmentCompleted ? "Shipped" : "Pending";
                    var gotBack = BigHelper.Orders.Update(orderId, toUpdate);

The response is:
      "The field 'id' cannot be written to. Please remove it from your request before trying again." 

Perplexed :( - any help out there? << I love this API - nicely done >>
walt@shipcaddie.com

**Comment by worstone** [comment]
Use a Anonymous Type to update the order, like the following.  Only send properties that are read-write, "id" & "status" is read-only.  

BTW "status" is a  read-only see [https://developer.bigcommerce.com/api/v2/#orders](https://developer.bigcommerce.com/api/v2/#orders)

```
public static void UpdateOrder(int orderId, int orderstatus) {

        //Use Anonymous Types - Like this to update a order

        var orderAnonymousOfType = new { status_id = orderstatus }; // not sure what the the status_ids are

        var response = Client.Orders.Update(orderId, orderAnonymousOfType);
    }

````
Should get you going.

**Comment by tossthekitty** [comment]
Super nice work bro!  I figured that out after I sent you the question.   Really awesome.
So far I've done Amazon, WooCommerce, BigCommerce and the Carriers - DHL, Stamps, Endicia (these were all done from scratch), UPS ... doing a ton more marketplaces and carriers.  Exciting work! - Amazing stuff!

BTW: WooCommerce is almost IDENTICAL in nature to BigCommerce.

Thank you for taking the time to get back to me.
walt@shipcaddie.com
