### ISSUE TITLE
Unable to Deserialize Response

### ISSUE THREAD

**Issue by samproc119** [worstone/BigCommerce4Net#7]
I am trying to deserialize a response from my BC store. However, I cannot work out how to properly use the built in BigCommerce4Net.Api.Deserializers.NewtonSoftJsonDeserializer. I am sure that this is due to plain ignorance on my part as I am unfamiliar with C#. 

My code is as follows. A nod in the right direction would be much appreciated. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Threading.Tasks;
using Api = BigCommerce4Net.Api;
using BigCommerce4Net.Domain;
using BigCommerce4Net.Api_Tests;
using NUnit.Framework;

namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {

            Api.Configuration Api_Configuration;

            Api_Configuration = new Api.Configuration()
            {
                ServiceURL = "***"
                UserName = "***",
                UserApiKey = "***",
                MaxPageLimit = 250,
                AllowDeletions = true // Is false by default, must be true to allow deletions
            };

            var Client = new Api.Client(Api_Configuration);
            Console.Write(Client+"\n");

            var response = Client.Countries.Count();
            Assert.AreEqual(response.RestResponse.StatusCode, System.Net.HttpStatusCode.OK);
            Assert.Greater(response.Data.Count, 0);

            Console.Write(response2.ToString() + "\n");

            Api.Deserializers.NewtonSoftJsonDeserializer Deserializer = new Api.Deserializers.NewtonSoftJsonDeserializer();

            Deserializer.Deserialize<>(response2); // I cannot work out what is required here.
        }
    }
}

Regards,
Sam

**Comment by worstone** [comment]
Sam,

The response.Data is deserialized automatically to a resource/domain object or List<> resource/domain object , you should never need to Deserialize the response from a client.

The client returns the IClientResponse<> interface 

https://github.com/worstone/BigCommerce4Net/blob/master/BigCommerce4Net.Api/Interfaces/IClientResponse.cs

All deserialization happens at the ClientBase

https://github.com/worstone/BigCommerce4Net/blob/master/BigCommerce4Net.Api/Client/ClientBase.cs

```csharp
var response = Client.Countries.Count(); // --  you will get -- IClientResponse<ItemCount> 
var response = Client.Countries.GetList(); // --  you will get --  IClientResponse<IList<Country>>
var response = Client.Countries.Ge(15); //  --  you will get --  IClientResponse<Country> 
```

Hope this helps

**Comment by samproc119** [comment]
Thank you for the fast reply,

I now understand where I've gone wrong and where to go next. 

Regards,
Sam
