### ISSUE TITLE
Product Customer Fields

### ISSUE THREAD

**Issue by MalcolmMck** [worstone/BigCommerce4Net#8]
Can anyone tell me the code structure for updating Custom Fields using the API. VB Code below is what I am using for Product Create and Update (C# example OK). There doesn't seem to be any direct methods for creating and updating Custom  and Configurable fields.

 Dim product = New With { name,  price,   description,  categories,  type,  availability,  weight,  sku,  upc,     is_visible  }

        If ID = 0 Then
            Dim ProductResponse = Client.Products.Create(product)
            If ProductResponse.ResponseErrors IsNot Nothing Then
                Return ProductResponse.ResponseErrors(0).Message.ToString()
            End If
            ID = ProductResponse.Data.Id
            Return ProductResponse.Data.Id.ToString
        Else

            Dim ProductResponse = Client.Products.Update(ID, product)
            If ProductResponse.ResponseErrors IsNot Nothing Then
                Return ProductResponse.ResponseErrors(0).Message.ToString()
            End If
            Return ProductResponse.Data.Id.ToString
        End If

**Comment by worstone** [comment]
Did you looked at ClientProductsCustomFields? https://github.com/worstone/BigCommerce4Net/blob/master/BigCommerce4Net.Api/Client/Products/ClientProductsCustomFields.cs

Have not looked at ProductsCustomFields in a few years, don't use them myself, but I am sure that is where you need to look.

You can't get at custom field from the ClientProducts

https://developer.bigcommerce.com/api/stores/v2/products/custom_fields
